name: Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "jaishree"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest
      # setp 5
      - name: Print name
        run: echo "eHello ${{ github.event.inputs.name}}"
